
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-fpm
  - php-cli
  - php-common
  - php-gd
  - php-mbstring
  - php-pdo
  - php-xml
  - php-curl
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
  - php-mysql

php_source_configure_command:

mysql_db: wordpress
mysql_user: wordpress
mysql_password: wordpress

mysql_databases:
  - name: "{{mysql_db}}"
    encoding: utf8
    collation: utf8_unicode_ci
mysql_users:
  - name: "{{mysql_user}}"
    host: "%"
    password: "{{mysql_password}}"
    priv: "wordpress.*:ALL"
