- hosts: all
  vars_files:
    - /var/ansible/roles/wp/vars/wp.yml
    - /var/ansible/roles/wp/vars/wp_vault.yml
  roles:
    - {role: common}
    - {role: geerlingguy.php}
    - {role: geerlingguy.mysql}
    - {role: wp, tags: [wp]}