---
# tasks file for common
- name: create directory
  file:
    path: /var/www/html
    state: directory

- name: download wp
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/html"
    remote_src: yes

- name: set ownership
  file:
    path: "/var/www/html"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: set permission for directories
  shell: "/usr/bin/find /var/www/html/ -type d -exec chmod 750 {} \\;"

- name: set permission for files
  shell: "/usr/bin/find /var/www/html/ -type f -exec chmod 640 {} \\;"

- name: setup wp-config
  template:
    src: "wp-config.php"
    dest: "/var/www/html/wordpress/wp-config.php"